name: yemu
description: TCP Chat Server
version: 1.0.0

environment:
  sdk: '>=2.18.3 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
dependencies:
  crypto: ^3.0.2
  encrypt: ^5.0.1
  jaguar: ^3.1.3
  pointycastle: ^3.6.2
  yaml: ^3.1.1
