name: yemu
description: TCP Chat Server
version: 1.0.0

environment:
  sdk: '>=2.18.3 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
dependencies:
  crypto: ^3.0.2
  jaguar: ^3.1.3
  yaml: ^3.1.1
  cryptography: ^2.0.5
  diffie_hellman:
    git: https://github.com/Amirust/diffie_hellman
  collection: ^1.17.0
